# Generated by Django 6.0.6 on 2026-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
