# Generated by Django 6.0.6 on 2026-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_shorturl_expires_at_alter_shorturl_click_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='life_time',
            field=models.CharField(choices=[('1h', '1 Hour'), ('1d', '1 Day'), ('1w', '1 Week'), ('never', 'Never')], default='never', max_length=10, verbose_name='URL Duration'),
        ),
    ]
