# Generated by Django 6.0.6 on 2026-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_shorturl_is_active_shorturl_life_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
